### PR TITLE
Replace CentOS 7 references with EL8

### PR DESCRIPTION
**Pull request by vishesh92**
----
📚 Documentation preview 📚: https://cloudstack-documentation--441.org.readthedocs.build/en/441/

### CODE REVIEW

**Review by sureshanaparti — APPROVED** [review]

**Comment by sureshanaparti** [comment]
@blueorangutan docbuild

**Comment by andrijapanicsb** [comment]
@blueorangutan docbuild

**Comment by andrijapanicsb** [comment]
@blueorangutan docbuild

**Comment by andrijapanicsb** [comment]
@blueorangutan docbuild

**Comment by andrijapanicsb** [comment]
@blueorangutan docbuild

**Comment by andrijapanicsb** [comment]
@blueorangutan docbuild

**Comment by andrijapanicsb** [comment]
@blueorangutan docbuild

**Comment by andrijapanicsb** [comment]
Updated the networking section with NMCLI commands - tested end-to-end

**Review by andrijapanicsb — APPROVED** [review]
LGTM

**Comment by DaanHoogland** [comment]
@blueorangutan docbuild

**Review by weizhouapache — APPROVED** [review]
lgtm

**Pull request merged**
