### PR TITLE
Add docs for scheduling operations on a VM

### PR DESCRIPTION
**Pull request by vishesh92**
Documentation for PR: https://github.com/apache/cloudstack/pull/7397

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
@blueorangutan docbuild 
 (@vishesh92 you can kick this yourself in future)

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
@blueorangutan docbuild

**Comment by vishesh92** [comment]
@blueorangutan docbuild

**Review by shwstppr — APPROVED** [review]
LGTM. Minor comment added

**Comment by vishesh92** [comment]
@blueorangutan docbuild

**Comment by vishesh92** [comment]
@blueorangutan docbuild

**Pull request merged**
