### PR TITLE
Add a list of supported ACS versions for live patching

### PR DESCRIPTION
**Pull request by Pearl1594**

### CODE REVIEW

**Comment by weizhouapache** [comment]
@Pearl1594 
can you add the new ACS version in the table ?

**Comment by weizhouapache** [comment]
> Sorry @weizhouapache didn't understand what you meant by new ACS version.

@Pearl1594 
I meant the cloudstack version after upgrade, for example it is `4.17.0.0` for now

**Comment by Pearl1594** [comment]
@blueorangutan docbuild

**Comment by Pearl1594** [comment]
@blueorangutan docbuild

**Comment by Pearl1594** [comment]
@blueorangutan docbuild

**Review by weizhouapache — APPROVED** [review]
code lgtm

thanks @Pearl1594 for the PR and intensive testing !

**Review by nvazquez — APPROVED** [review]

**Pull request merged**
