### PR TITLE
Add CreateConsoleEndpoint docs

### PR DESCRIPTION
**Pull request by nvazquez**
PR link: https://github.com/apache/cloudstack/pull/6577

### CODE REVIEW

**Comment by nvazquez** [comment]
@blueorangutan docbuild

**Comment by nvazquez** [comment]
@blueorangutan docbuild

**Comment by nvazquez** [comment]
@blueorangutan docbuild

**Comment by nvazquez** [comment]
@blueorangutan docbuild

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
@borisstoyanov can you review/lgtm this doc changes?

**Comment by rohityadavcloud** [comment]
Merged as I have been advised lgtm

**Pull request merged**
