### PR TITLE
Primate docs with 4.14 release

### PR DESCRIPTION
**Pull request by rhtyd**
Primate docs to go with 4.14 docs

### CODE REVIEW

**Comment by rhtyd** [comment]
request docbuild

**Comment by rhtyd** [comment]
request docbuild

**Comment by rhtyd** [comment]
request docbuild

**Comment by rhtyd** [comment]
@andrijapanicsb please review and merge. Can you help add a deprecation/information notice in the release notes `source/releasenotes/about.rst` (we basically want to add a link to the Primate install page and say that UI will be deprecated in future CloudStack release due to Primate...).

**Comment by rhtyd** [comment]
Primate install page here: https://acs-www.shapeblue.com/docs/WIP-PROOFING/pr122/installguide/primate.html

**Comment by rhtyd** [comment]
request docbuild

**Comment by rhtyd** [comment]
request docbuild

**Comment by rhtyd** [comment]
request docbuild

**Comment by rhtyd** [comment]
request docbuild

**Comment by rhtyd** [comment]
request docbuild

**Comment by andrijapanicsb** [comment]
@rhtyd @PaulAngus I'll need to merge this one as it is - for cutting the 4.14 docs branch, etc. - but we can update this if needed with a new PR against the 4.14 branch and I can easily rebuild the docs

**Pull request merged**
