### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by davidjumani**

### CODE REVIEW

**Comment by rhtyd** [comment]
@davidjumani conflict on master branch, or is it for 4.15 branch?

**Comment by davidjumani** [comment]
@rhtyd It's for 4.15, to be merged after #207 is merged

**Comment by davidjumani** [comment]
@blueorangutan docbuild

**Comment by rhtyd** [comment]
@davidjumani pl address merge conflicts

**Comment by davidjumani** [comment]
@rhtyd Conflicts resolved

**Comment by rhtyd** [comment]
@andrijapanicsb are you lgtm on this cc @DaanHoogland

**Comment by andrijapanicsb** [comment]
LGTM in regards to the new images.

I have not reviewed tons of other space and indentation changes

**Review by andrijapanicsb — APPROVED** [review]

**Comment by DaanHoogland** [comment]
ok, let's merge, we can always amend as we go (it's only confusing docs anyways) , @rhtyd ?

**Pull request merged**
