### PR TITLE
Modernizing "Create linux template" guide + Cloud-init integration steps

### PR DESCRIPTION
**Pull request by dredknight**
The following sections are redone:
1. Working with templates -> Creating a Linux Template
--- guide was readjusted in more linear fashion. 
--- Removed Ubuntu hostname warning as it is not relevant for Ubuntu OS versions since 2020
--- Removed a command on how to become root in password management section
--- "Master template" definition changed to "Main template"
--- added links to a new section "Cloud-init integration" (check below)

2. Added new section Working with templates -> Cloud-init integration
--- added as possible addition to Working with templates -> Creating a Linux Template
--- Showcased features and examples related to Cloudstack instances features such as: password management, ssh-keys management, partition management, user-data input

### CODE REVIEW

**Comment by andrijapanicsb** [comment]
@dredknight can you please resolve the conflict? Thx

**Comment by andrijapanicsb** [comment]
@blueorangutan docbuild

**Comment by dredknight** [comment]
Thank you! I will resolve them + will add some minor changes to the guide.

**Comment by dredknight** [comment]
Conflicts are now resolved
Fixed some links that were not working properly in _create_linux.rst file
One of the internal references there is made with external reference link as I could not find a way to do it with internal link:
*  `Implementing a SSH-Key bash script <http://docs.cloudstack.apache.org/en/latest/adminguide/virtual_machines.html#creating-an-instance-template-that-supports-ssh-keys>`_

**Comment by rhtyd** [comment]
@blueorangutan docbuild

**Comment by dredknight** [comment]
Tested the preview there were 2 broken links in the cloud-init integration section. 
Commit https://github.com/apache/cloudstack-documentation/pull/215/commits/498046aeca0778d9f97b16455bc642380aeea059 fixes them.

**Comment by dredknight** [comment]
@andrijapanicsb I believe this is done now.

**Comment by rhtyd** [comment]
@blueorangutan docbuild

**Comment by rhtyd** [comment]
Hi @dredknight a user from mailing list has given following suggestion:
```
> Hello everyone.
>
> I've been following the Cloud-init integration guides in the ACS 4.16
> documentation and noticed a problem with Ubuntu Server 20.04 LTS. In
> particular, the section "Specify the managed user" shows:
>
> system_info : default_user : name : cloud - user lock_passwd : false # disable
> user password login - true/false sudo : [ \ "ALL=(ALL) ALL \" ]       # User
> permissions disable_root : 0 # root remote login is 0 - enabled, 1 - disabled
> ssh_pwauth : 1 # password login is 0 - disabled, 1- enabled
>
> Adding this produces an error message when trying to use sudo. The error message
> is:
>
> $ sudo su
>>>> /etc/sudoers.d/90-cloud-init-users: syntax error near line 4 <<<
> sudo: parse error in /etc/sudoers.d/90-cloud-init-users near line 4
> sudo: no valid sudoers sources found, quitting
> sudo: unable to initialize policy plugin
>
> Removing the "\" in
> sudo : [ \ "ALL=(ALL) ALL \" ]
> seem to fix the problem for me.
```

Mailing list thread reference: https://markmail.org/message/ruxyqzs44lqjtqpf

**Comment by dredknight** [comment]
Thanks Rohit!

I will test next week and update.

**Comment by DaanHoogland** [comment]
@dredknight @rhtyd It seems to me (at first sight that not the "\" but the space behind it should be removed. just FYI

**Comment by dredknight** [comment]
@nvazquez yes it is.

**Comment by weizhouapache** [comment]
@blueorangutan docbuild

**Review by weizhouapache — APPROVED** [review]
lgtm

**Comment by dredknight** [comment]
@weizhouapache mold it as you see it fit. If they are not looking good they can be scrapped.

**Comment by nvazquez** [comment]
@weizhouapache @dredknight I have restored the images - now changes include only the .rst files

**Comment by nvazquez** [comment]
@blueorangutan docbuild

**Comment by nvazquez** [comment]
@dredknight the navigation to the Cloud-init section through the 'Create Linux Template' section gives a 404 error, can you please check the links?

**Comment by dredknight** [comment]
@nvazquez sorry for the late response.

I checked the [QA page](http://qa.cloudstack.cloud/docs/WIP-PROOFING/pr/215/adminguide/templates/_create_linux.html) and did not find any. Can you point me where is the link?

I see 4 links and all of them are working
image

**Pull request merged**
