### PR TITLE
Update vsphere.rst

### PR DESCRIPTION
**Pull request by borisstoyanov**
update latest versions of VMware

I'm not sure if I did that right with the dynamic selection of versions, could someone advise or doublecheck please. We don't want to show this appear with older versions for example

----
📚 Documentation preview 📚: https://cloudstack-documentation--387.org.readthedocs.build/en/387/

### CODE REVIEW

**Comment by borisstoyanov** [comment]
@blueorangutan docbuild

**Comment by borisstoyanov** [comment]
link seems to be working

**Comment by weizhouapache** [comment]
> link seems to be working

cool

can the versions on the page be removed ? @borisstoyanov

**Comment by borisstoyanov** [comment]
done @weizhouapache

**Review by weizhouapache — APPROVED** [review]
looks good, thanks @borisstoyanov 

image


https://cloudstack-documentation--387.org.readthedocs.build/en/387/installguide/hypervisor/vsphere.html

**Pull request merged**
