### PR TITLE
veeam: update API commands and versions in doc

### PR DESCRIPTION
**Pull request by weizhouapache**
----
📚 Documentation preview 📚: https://cloudstack-documentation--357.org.readthedocs.build/en/357/

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]

**Review by borisstoyanov — APPROVED** [review]
LGTM

**Comment by weizhouapache** [comment]
@blueorangutan docbuild

**Comment by weizhouapache** [comment]
@blueorangutan docbuild

**Comment by weizhouapache** [comment]
@blueorangutan docbuild

**Comment by weizhouapache** [comment]
looks ok
https://qa.cloudstack.cloud/builds/docs-build/pr/357/adminguide/veeam_plugin.html

**Pull request merged**
