### PR TITLE
Update user-data.rst

### PR DESCRIPTION
**Pull request by NPdocker**
Update syntax for cloud-init

### CODE REVIEW

**Comment by rhtyd** [comment]
LGTM, we need one more review, can you check @weizhouapache @onitake thnx

**Comment by onitake** [comment]
Hi @NPdocker - can you clarify why this PR is necessary?
Was there a configuration format change in cloud-init?

**Comment by rhtyd** [comment]
With the other PR merged, do we need this - can you check and advise @onitake @NPdocker @weizhouapache ?

**Comment by weizhouapache** [comment]
@rhtyd 
I have same question as @onitake .
we use the old config in vms, it works fine.
```
      datasource:
        CloudStack: {}
        None: {}
      datasource_list:
        - CloudStack
 ```

**Comment by onitake** [comment]
I think the reason for the previous stanza was that older cloud-init versions did not propagate anything without explicitly mentioning CloudStack both in `datasource` and `datasource_list`. This might have changed, or the missing `None` in `datasource_list` prevented it from working.

@Doni7722 Could you verify if `datasource_list: [ CloudStack, None ]` without `datasource` works for us? Thanks!

**Comment by Doni7722** [comment]
@onitake I'll test that today and let you know the results.

**Comment by Doni7722** [comment]
@onitake I did verify and can confirm that it works fine with `datasource_list: [ CloudStack, None ]` without `datasource`

**Pull request merged**
