### PR TITLE
Adding cloudstack-kubernetes-provider docs

### PR DESCRIPTION
**Pull request by davidjumani**
Adds the documentation for https://github.com/apache/cloudstack-kubernetes-provider prior to it's release

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan docbuild

**Comment by davidjumani** [comment]
@blueorangutan docbuild

**Comment by davidjumani** [comment]
@blueorangutan docbuild

**Comment by davidjumani** [comment]
@onitake @joschi36 Can you review ?

**Review by shwstppr — APPROVED** [review]
LGTM
@davidjumani if your changes final, please set PR ready for review

**Comment by davidjumani** [comment]
@blueorangutan docbuild

**Comment by davidjumani** [comment]
@blueorangutan docbuild

**Comment by davidjumani** [comment]
@blueorangutan docbuild

**Pull request merged**
