### PR TITLE
CLOUDSTACK-10399: Added section regarding MySQL server-id

### PR DESCRIPTION
**Pull request by falcon78921**
Fixes CLOUDSTACK-10399: Specify MySQL server-id for later versions of CloudStack

Signed-off-by: James McClune <jmcclune@mcclunetechnologies.net>

### CODE REVIEW

**Comment by falcon78921** [comment]
@rafaelweingartner Thanks Rafael! :)

**Comment by falcon78921** [comment]
Hello @GabrielBrascher @rafaelweingartner,

The changes I've submitted are merged into the ```master``` branch. However, I've noticed they haven't been built into the latest docs. Are the docs built on a scheduled basis?

**Comment by PaulAngus** [comment]
Hi @falcon78921,
Changes in the Master branch will only be seen in the next release, ie 4.12.
The reason being that it will have information which will related to features that aren't available yet.
For changes to be seen right now, they would need to be backported to the 4.11 branch, and the current tag (4.11.2) moved to the latest commit.
(yes it seems far more complicated that it need be, but what can you do).

**Comment by falcon78921** [comment]
Thanks @PaulAngus for the followup.

**Pull request merged**
