### PR TITLE
Reserve public IP address for accounts

### PR DESCRIPTION
**Pull request by weizhouapache**
This links to https://github.com/apache/cloudstack/pull/6046

### CODE REVIEW

**Comment by DaanHoogland** [comment]
> @blueorangutan ui
maybe you meant
@blueorangutan docbuild

**Comment by weizhouapache** [comment]
@blueorangutan docbuild

**Comment by weizhouapache** [comment]
@blueorangutan docbuild

**Comment by weizhouapache** [comment]
> 

@DaanHoogland yes, you are absolutely right  :-D thanks

**Review by nvazquez — APPROVED** [review]

**Pull request merged**
