### PR TITLE
VM Autoscaling with virtual router

### PR DESCRIPTION
**Pull request by weizhouapache**
This is for PR https://github.com/apache/cloudstack/pull/6571

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueoranguran docbuild

**Comment by weizhouapache** [comment]
@blueorangutan docbuild

**Comment by weizhouapache** [comment]
@blueorangutan docbuild

**Comment by weizhouapache** [comment]
@blueorangutan docbuild

**Comment by weizhouapache** [comment]
@blueorangutan docbuild

**Comment by weizhouapache** [comment]
@blueorangutan docbuild

**Comment by weizhouapache** [comment]
@blueorangutan docbuild

**Comment by weizhouapache** [comment]
@blueorangutan docbuild

**Comment by weizhouapache** [comment]
@blueorangutan docbuild

**Comment by weizhouapache** [comment]
@blueorangutan docbuild

**Comment by weizhouapache** [comment]
@blueorangutan docbuild

**Comment by weizhouapache** [comment]
@blueorangutan docbuild

**Comment by weizhouapache** [comment]
@blueorangutan docbuild

**Comment by weizhouapache** [comment]
@blueorangutan docbuild

**Comment by rohityadavcloud** [comment]
@blueorangutan docbuild

**Comment by rohityadavcloud** [comment]
@blueorangutan docbuild

**Comment by weizhouapache** [comment]
this is the documentation for merged PR https://github.com/apache/cloudstack/pull/6571
could you review and merge it ? thanks

**Comment by weizhouapache** [comment]
https://qa.cloudstack.cloud/builds/docs-build/pr/286/adminguide/autoscale_with_virtual_router.html

**Comment by rohityadavcloud** [comment]
@blueorangutan docbuild

**Review by DaanHoogland — APPROVED** [review]

**Pull request merged**
