### PR TITLE
NSX Integration Documentation

### PR DESCRIPTION
**Pull request by nvazquez**
Docs for PR: https://github.com/apache/cloudstack/pull/7919

----
📚 Documentation preview 📚: https://cloudstack-documentation--378.org.readthedocs.build/en/378/

### CODE REVIEW

**Comment by Pearl1594** [comment]
@blueorangutan docbuild

**Comment by Pearl1594** [comment]
@blueorangutan docbuild

**Review by NuxRo — APPROVED** [review]
LGTM

**Comment by nvazquez** [comment]
@blueorangutan docbuild

**Review by Pearl1594 — APPROVED** [review]
LGTM.
Not sure if we want to add a small note on adding support for non-rfc1918 compliant IPs.

**Pull request merged**
