### PR TITLE
Ipmitool version

### PR DESCRIPTION
**Pull request by Spaceman1984**
Added a note about Host HA migration failure on Centos 8 as per https://github.com/apache/cloudstack/issues/4204

### CODE REVIEW

**Comment by Spaceman1984** [comment]
requesting docbuild

**Comment by Spaceman1984** [comment]
@andrijapanicsb @shwstppr  @rhtyd, please review.

**Comment by andrijapanicsb** [comment]
the preview is not available, but a simple change, thus LGTM

**Review by andrijapanicsb — APPROVED** [review]

**Comment by andrijapanicsb** [comment]
requesting docbuild

**Review by GabrielBrascher — APPROVED** [review]
LGTM

**Pull request merged**
