### PR TITLE
Improve warning about the unauthenticated API port

### PR DESCRIPTION
**Pull request by onitake**
Changes:

- Added a warning box around the note about port 8096
- Improved wording slightly
- Added a note at the end on how to disable unauthenticated mgmt server access

### CODE REVIEW

**Comment by onitake** [comment]
Note: I didn't test if it renders correctly in sphinx.
The `.. warning::` was simply copied from the documentation - I assumed it would work.

**Comment by rhtyd** [comment]
@onitake I'll have to build and check

**Comment by rhtyd** [comment]
requesting docbuild

**Comment by rhtyd** [comment]
Build/changes LGTM from the doc:
Screenshot from 2019-07-12 13-18-20

**Comment by onitake** [comment]
Great, thanks!

**Pull request merged**
