### PR TITLE
Guest OS and hypervisor mappings

### PR DESCRIPTION
**Pull request by harikrishna-patnala**
This documentation is related to the PR https://github.com/apache/cloudstack/pull/6979 which is for the improved guest OS and hypervisor mappings.

### CODE REVIEW

**Comment by harikrishna-patnala** [comment]
@blueorangutan docbuild

**Comment by weizhouapache** [comment]
@blueorangutan docbuild

**Review by weizhouapache — APPROVED** [review]
doc looks good
https://qa.cloudstack.cloud/builds/docs-build/pr/300/adminguide/guest_os.html

**Review by vladimirpetrov — APPROVED** [review]
LGTM

**Comment by harikrishna-patnala** [comment]
related code PR is also merged

**Pull request merged**
