### PR TITLE
4.15 Release & Upgrade Notes

### PR DESCRIPTION
**Pull request by rhtyd**
- [x] 4.15 systemvm upgrade steps
- [x] 4.15 in conf.py for version
- [x] 4.15 known issues boiler plate
- [x] EOL for CentOS 6.x, MySQL 5.5, vSphere 6.0 (https://cwiki.apache.org/confluence/display/CLOUDSTACK/Hypervisor+and+Management+Server+OS+EOL+Dates)
- [x] New support added for Ubuntu 20.04, CentOS/RHEL 8.x, XCP-ng 8.0/8.1, MySQL 8.0; browser versions updated
- [x] UI deprecation/removal notice
- [x] Check Primate related docs, repo/instructions wrt 1.0/GA

### CODE REVIEW

**Comment by rhtyd** [comment]
requesting docbuild

**Comment by rhtyd** [comment]
requesting docbuild

**Comment by rhtyd** [comment]
@davidjumani can you update the section on Primate installation from CloudStack repo vs sepately (both)

**Comment by davidjumani** [comment]
requesting docbuild

**Comment by davidjumani** [comment]
@rhtyd Changes made. Could you please review ?

**Comment by rhtyd** [comment]
LGTM thanks @davidjumani for the instructions fixes

@PaulAngus @DaanHoogland can you review and merge, what is remaining is still the list of issues fixes and known issues. Rest I think most of the sections are covered. cc @borisstoyanov @vladimirpetrov

**Comment by rhtyd** [comment]
If there are no objections I'll merge this, any new changes can be submitted as new PR

requesting docbuild

**Review by DaanHoogland — APPROVED** [review]

**Comment by DaanHoogland** [comment]
as you stated @rhtyd , we'll need addtional changes, but it doesn't matter if we add them here or in a new PR.

**Review by GabrielBrascher — APPROVED** [review]

**Pull request merged**
