### PR TITLE
Added basic and advanced customization sections to the primate doc

### PR DESCRIPTION
**Pull request by Pearl1594**
Added details :
Basic customization: modifying themes, adding custom plugins
Advanced customization: Adding new sections

Addresses: https://github.com/apache/cloudstack-primate/issues/464

### CODE REVIEW

**Comment by Pearl1594** [comment]
requesting docbuild

**Comment by davidjumani** [comment]
requesting docbuild

**Comment by davidjumani** [comment]
requesting docbuild

**Comment by davidjumani** [comment]
requesting docbuild

**Comment by davidjumani** [comment]
requesting docbuild

**Comment by davidjumani** [comment]
@rhtyd Good to go!

**Comment by Pearl1594** [comment]
requesting docbuild

**Comment by Pearl1594** [comment]
Looks good

**Comment by davidjumani** [comment]
requesting docbuild

**Comment by davidjumani** [comment]
requesting docbuild

**Comment by rhtyd** [comment]
I'll review this again against latest master wrt known limitations sections. Install and customisation sections LGTM.

**Comment by davidjumani** [comment]
requesting docbuild

**Comment by rhtyd** [comment]
requesting docbuild

**Review by rhtyd — APPROVED** [review]

**Pull request merged**
