### PR TITLE
Updating image and docs wrt the new UI

### PR DESCRIPTION
**Pull request by davidjumani**

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan docbuild

**Comment by davidjumani** [comment]
@blueorangutan docbuild

**Comment by davidjumani** [comment]
@blueorangutan docbuild

**Review by shwstppr — APPROVED** [review]
LGTM. Haven't verified each page but `source/_static/images` contains new icons and images. The pages I checked display new images as well. Minor change for enable-disable icon already applied.
Thanks for the effort @davidjumani

**Comment by davidjumani** [comment]
@blueorangutan docbuild

**Comment by davidjumani** [comment]
@blueorangutan docbuild

**Comment by andrijapanicsb** [comment]
LGTM

**Pull request merged**
