### PR TITLE
Add documentation for Cluster DRS

### PR DESCRIPTION
**Pull request by vishesh92**
Documentation for DRS feature in https://github.com/apache/cloudstack/pull/7723

### CODE REVIEW

**Comment by vishesh92** [comment]
@blueorangutan docbuild

**Comment by vishesh92** [comment]
@blueorangutan docbuild

**Comment by vishesh92** [comment]
@blueorangutan docbuild

**Comment by shwstppr** [comment]
ping @alexandremattioli @kiranchavala for review

**Review by kiranchavala — APPROVED** [review]
LGTM

**Comment by DaanHoogland** [comment]
@blueorangutan docbuild

**Comment by vishesh92** [comment]
@blueorangutan docbuild

**Pull request merged**
