### PR TITLE
Volumes metrics doc update

### PR DESCRIPTION
**Pull request by andrijapanicsb**
Volume metrics doc/explanation

### CODE REVIEW

**Comment by andrijapanicsb** [comment]
requesting docbuild

**Comment by andrijapanicsb** [comment]
The new section here: https://acs-www.shapeblue.com/docs/pr60/adminguide/storage.html#volume-metrics

@nvazquez @anuragaw @shwstppr - kindly review and LGTM.

**Comment by rhtyd** [comment]
@andrijapanicsb can you address conflict and move to ready for review when this is ready?

**Comment by rhtyd** [comment]
cc @Spaceman1984

**Comment by nvazquez** [comment]
@andrijapanicsb can you please fix the conflicts and advise if this is ready? I think also the picture needs to be updated to the new UI

**Comment by andrijapanicsb** [comment]
requesting docbuild

**Comment by andrijapanicsb** [comment]
@blueorangutan docbuild

**Comment by andrijapanicsb** [comment]
@blueorangutan docbuild

**Review by GabrielBrascher — APPROVED** [review]

**Comment by andrijapanicsb** [comment]
@blueorangutan docbuild

**Comment by andrijapanicsb** [comment]
done @nvazquez  - good spot. THx.

**Review by nvazquez — APPROVED** [review]

**Pull request merged**
