### PR TITLE
AutoScaling: add reset data of vm instances

### PR DESCRIPTION
**Pull request by weizhouapache**
this is the doc PR for https://github.com/apache/cloudstack/pull/7769

please check the new page on https://qa.cloudstack.cloud/builds/docs-build/pr/335/adminguide/autoscale_with_virtual_router.html#updating-autoscale-vm-profile

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan docbuild

**Comment by weizhouapache** [comment]
@blueorangutan docbuild

**Comment by weizhouapache** [comment]
@blueorangutan docbuild

**Comment by weizhouapache** [comment]
@blueorangutan docbuild

**Review by harikrishna-patnala — APPROVED** [review]
LGTM

In "Adding an AutoScale VM Group" section
image

In reset section
image

**Comment by borisstoyanov** [comment]
@blueorangutan docbuild

**Pull request merged**
