### PR TITLE
remove blacklist and whitelist phrases

### PR DESCRIPTION
**Pull request by PaulAngus**
small alterations to remove the phrases blacklist and whitelist

### CODE REVIEW

**Comment by rhtyd** [comment]
@DaanHoogland @PaulAngus you may need to re-open the PR and merge only after the upstream PR to apache/cloudstack is merged with a DB upgrade path too

**Comment by PaulAngus** [comment]
theres a closed pull for an empty DB path (https://github.com/apache/cloudstack/pull/4092) do you happen to know if/what the PR for one with contents in ?  (i can't find one)

**Comment by DaanHoogland** [comment]
I don't think I understand your question @PaulAngus . Are you asking whether any PR added DB changes to the file?
if so:
```
cfbb4ff3dd5a53f55040d3345b96bc7e97964eb2 - schema: change upgrade path to 4.14 (from 4.13) and intensify check (#4331)(Pearl Dsilva)
d949302d0f6805b895307f68a561762bcbc87aff - packaging: Adding Centos8, Ubuntu 20.04, XCPNG8.1 Support (#4068)(davidjumani)
c578004fe5f049684830d4323422dc3953481ac7 - projects: Role based users in Projects (#4128)(Pearl Dsilva)
64c69389db7fbf45784baef28f3f5e8bcd084ff9 - db: VMware Guest OS Mappings fix (#4196)(Andrija Panic)
5040283db9744175402b53ba9a6c701b9d8e3436 - server: Dynamic roles improvements. Add-on functionality below. (#4071)(sureshanaparti)
d0d346524bd04a8b1691c1a0b7fe36ea23d4311c - schema: add empty DB upgrade path from 4.14.0.0 to 4.15.0.0 (#4092)(Abhishek Kumar)
```

**Comment by rhtyd** [comment]
@PaulAngus the backend PR for this doc change hasn't been merged, so this was reverted and Daan re-opened a PR with the changes - https://github.com/apache/cloudstack-documentation/pull/155

**Comment by rhtyd** [comment]
The backend PR for this doc PR is - https://github.com/apache/cloudstack/pull/4135

**Pull request merged**
