### PR TITLE
Restart system vms to MASTER

### PR DESCRIPTION
**Pull request by andrijapanicsb**
@PaulAngus this one contains same "include rebooting systemsVM" as PR #79 , but here also your own changes around guest OS customisation (and some headers and references chagnes) are included.
I believe this is all required for master.
Later we'll need to update versions to 4.14 etc (one it's out)

### CODE REVIEW

**Comment by PaulAngus** [comment]
@andrijapanicsb - I've merged 4.13 branch into master, can you rebase this PR to see what (if any) 'changes' are left

**Comment by andrijapanicsb** [comment]
Done @PaulAngus

**Comment by PaulAngus** [comment]
Should this not go into 4.13 so that we can forward merge?

**Comment by andrijapanicsb** [comment]
@PaulAngus I've made originally a PR against 4.13 as well - currently contains identical commits - so if you are OK, we can merge both PR?

**Comment by PaulAngus** [comment]
Are you saying that the content of the commit is the same or that the commit SHA is the same? @andrijapanicsb

**Comment by andrijapanicsb** [comment]
6 commits each, same SHA:

image

**Comment by andrijapanicsb** [comment]
merged to 4.13, merged forward to master - so closing this one.

**Pull request closed without merging**
