### PR TITLE
Add documentation for storage management

### PR DESCRIPTION
**Pull request by vishesh92**
Documentation for https://github.com/apache/cloudstack/pull/7949

### CODE REVIEW

**Comment by vishesh92** [comment]
@blueorangutan docbuild

**Review by kiranchavala — APPROVED** [review]
LGTM, the documentation is fine

**Review by shwstppr — APPROVED** [review]
LGTM

**Comment by shwstppr** [comment]
ping @alexandremattioli for review

**Comment by alexandremattioli** [comment]
LGTM

**Pull request merged**
