### PR TITLE
OAuth 2.0 integration

### PR DESCRIPTION
**Pull request by harikrishna-patnala**
This is related to the PR https://github.com/apache/cloudstack/pull/7996

oauth-login

### CODE REVIEW

**Comment by harikrishna-patnala** [comment]
@blueorangutan docbuild

**Review by DaanHoogland — APPROVED** [review]
text looks good @harikrishna-patnala , but does it make sense to add API based configuration instructions?

**Comment by harikrishna-patnala** [comment]
@blueorangutan docbuild

**Comment by harikrishna-patnala** [comment]
> text looks good @harikrishna-patnala , but does it make sense to add API based configuration instructions?

Okay @DaanHoogland I think not all are APIs are required, but registerOAuthProvider makes sense to add. I'll add it.

**Comment by DaanHoogland** [comment]
@blueorangutan docbuild

**Comment by harikrishna-patnala** [comment]
@blueorangutan docbuild

**Comment by DaanHoogland** [comment]
@harikrishna-patnala why do we need two pictures of the login page with "testdomain"? these could be shared right?

**Review by rohityadavcloud — APPROVED** [review]
LGTM

**Comment by rohityadavcloud** [comment]
@harikrishna-patnala if there any further changes, pl raise another doc PR and ping me.

**Pull request merged**
