### PR TITLE
Added details to the stickiness policy under load balancing

### PR DESCRIPTION
**Pull request by harikrishna-patnala**
Here I've added details to explain different stickiness methods and options provided to configure.

### CODE REVIEW

**Comment by harikrishna-patnala** [comment]
@blueorangutan docbuild

**Comment by harikrishna-patnala** [comment]
Here it is https://qa.cloudstack.cloud/builds/docs-build/pr/312/adminguide/networking_and_traffic.html#sticky-session-policies-for-load-balancer-rules

**Review by rohityadavcloud — APPROVED** [review]

**Review by borisstoyanov — APPROVED** [review]
LGTM

**Comment by andrijapanicsb** [comment]
@DaanHoogland please see if this can be included to the 4.18.1 release as well, since the related UI changes will be part of 4.18.1+

**Comment by andrijapanicsb** [comment]
cc @harikrishna-patnala  ^^^

**Comment by harikrishna-patnala** [comment]
@andrijapanicsb the related [PR#7434](https://github.com/apache/cloudstack/pull/7434) was merged in main for 4.19. We may need to port both PRs back to 4.18 branch. Not sure if this will create forward merge conflicts.

**Comment by andrijapanicsb** [comment]
My point is - we have to have the documentation updated for whatever branch the original UI changes are done (I see 4.18.1 as the milestone for the UI changes, so the docs also needs to be there for the same branch/release).

I leave to you experts to do the magic ;)

**Pull request merged**
