### PR TITLE
ui: add userCard configuration details

### PR DESCRIPTION
**Pull request by rohityadavcloud**

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
@blueorangutan docbuild

**Review by shwstppr — APPROVED** [review]
Change looks good

**Comment by rohityadavcloud** [comment]
Thanks @DaanHoogland but JFYI the related PR isn't merged yet https://github.com/apache/cloudstack/pull/7956

**Comment by DaanHoogland** [comment]
ok, my bad (but now we have to;)

**Pull request merged**
