### PR TITLE
CloudStack Kubernetes Service

### PR DESCRIPTION
**Pull request by shwstppr**
Documentation for CloudStack Kubernetes Service feature
Feature PR: https://github.com/apache/cloudstack/pull/3680/

### CODE REVIEW

**Comment by shwstppr** [comment]
requesting docbuild

**Comment by shwstppr** [comment]
requesting docbuild

**Comment by andrijapanicsb** [comment]
ping @shwstppr do we need more updates, can we get this ready for 4.14?

**Comment by shwstppr** [comment]
requesting docbuild

**Comment by shwstppr** [comment]
@andrijapanicsb this is ready for 4.14 and for review
@PaulAngus can you please have a look

**Comment by andrijapanicsb** [comment]
@shwstppr is this good for merging?

**Comment by andrijapanicsb** [comment]
Guys, can we get this one in - has anyone reviewed it?
Need it for 4.14 asap

/cc @PaulAngus @rhtyd

**Comment by PaulAngus** [comment]
request docbuild

**Comment by PaulAngus** [comment]
request docbuild

**Comment by PaulAngus** [comment]
I've moved some stuff around and made parameter lists more readable (removed horizontal scrolling).

I'm OK with it to go in.

**Pull request merged**
