### PR TITLE
Volume snap policies doc update

### PR DESCRIPTION
**Pull request by andrijapanicsb**
Volume snapshots can have tags associated with it (both manual and scheduled ones).
Minor general volume snapshot updates

### CODE REVIEW

**Comment by andrijapanicsb** [comment]
requesting docbuild

**Comment by andrijapanicsb** [comment]
requesting docbuild

**Comment by andrijapanicsb** [comment]
requesting docbuild

**Comment by andrijapanicsb** [comment]
@borisstoyanov @anuragaw @nvazquez @shwstppr - someone kindly review and LGTM if OK.

**Comment by PaulAngus** [comment]
requesting docbuild

**Pull request closed without merging**
