### PR TITLE
Non-strict affinity groups: update doc and add examples

### PR DESCRIPTION
**Pull request by weizhouapache**
This is the doc for https://github.com/apache/cloudstack/pull/6845

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan docbuild

**Comment by weizhouapache** [comment]
http://qa.cloudstack.cloud/docs/WIP-PROOFING/pr/291/adminguide/virtual_machines.html#determine-destination-host-of-vms-with-non-strict-affinity-groups

**Comment by weizhouapache** [comment]
@blueorangutan docbuild

**Comment by weizhouapache** [comment]
@blueorangutan docbuild

**Comment by weizhouapache** [comment]
@blueorangutan docbuild

**Comment by rohityadavcloud** [comment]
@blueorangutan docbuild

**Review by alexandremattioli — CHANGES_REQUESTED** [review]
By defining affinity groups and assigning VMs to them, the user or administrator can influence which VMs should run on either the same or separate hosts. This feature allows users to specify the affinity groups to which a VM can belong. VMs with the same “host anti-affinity” type won’t be placed on the same host, which serves to increase fault tolerance. If a host fails, another VM offering the same service (for example, hosting the user's website) is still up and running on another host. It also lets the user specify that VMs with the same "host affinity" type must run on the same host, which can be useful in ensuring connectivity and low latency between guest VMs. "non-strict host anti-affinity" is similar to, but more flexible than, "host anti-affinity". In that case VMs are deployed to different hosts as long as there are enough hosts to satisfy the requirement, otherwise they might be deployed to the same host. "non-strict host affinity" is similar but more flexible than "host affinity", VMs are ideally placed together in the same host, but only if possible.
The scope of an affinity group is on an account level.

**Review by alexandremattioli — CHANGES_REQUESTED** [review]
Type. CloudStack supports four types of affinity groups. "host anti-affinity", "host affinity", "non-strict host affinity" and "non-strict host anti-affinity". "host anti-affinity" indicates that the VMs in this group must not be placed on the same host. "host affinity" on the other hand indicates that VMs in this group must place on the same host. "non-strict host anti-affinity" indicates that VMs in this group should be deployed to different hosts. "non-strict host affinity" indicates that VMs in this group shouldn’t be deployed to same hosts.

**Comment by weizhouapache** [comment]
thanks @alexandremattioli , update

@blueorangutan docbuild

**Comment by weizhouapache** [comment]
@blueorangutan docbuild

**Review by DaanHoogland — APPROVED** [review]

**Pull request merged**
