### PR TITLE
Updated the linux password script location

### PR DESCRIPTION
**Pull request by glennwagner**

### CODE REVIEW

**Comment by GabrielBrascher** [comment]
@glennwagner thanks for the PR.
Just wondering, wouldn't it be better to point this PR to the apache:master instead of apache:4.11?

**Comment by glennwagner** [comment]
Master has been updated already the docs page uses  the 4.11.2 tag which seems to  comes from the 4.11 branch

**Comment by glennwagner** [comment]
unless we move the 4.11.2 tag to master, that will work too

**Comment by rafaelweingartner** [comment]
So, the idea is to merge in 4.11, and then push forward to master, right?

**Comment by andrijapanic** [comment]
no, it's already present in master, but we want it fixed in 4.11.2 (current doc)

**Comment by GabrielBrascher** [comment]
Got it. Thanks!

**Pull request merged**
