### PR TITLE
Add improvements on DPDK documentation

### PR DESCRIPTION
**Pull request by nvazquez**
Include documentation for final fixes on DPDK support feature for KVM

### CODE REVIEW

**Comment by DennisKonrad** [comment]
LGTM 
as future user of CS with DPDK I would appreciate even more doucmentation on this ;)

**Comment by nvazquez** [comment]
Thanks for your reviews!
@DennisKonrad I have added more documentation on this PR on the latest commit

**Comment by rafaelweingartner** [comment]
@nvazquez and @DennisKonrad can we merge? Or, maybe you guys would like some more time to review and improve things

**Comment by DennisKonrad** [comment]
@rafaelweingartner I read through it and at least for me it's clear now how one can configure VMs using DPDK

LGTM

**Pull request merged**
