### PR TITLE
Add warning about customisations when upgrading

### PR DESCRIPTION
**Pull request by andrijapanicsb**
explanation and "note" in separate file - included in upgrade steps for 4.12/4.11/4.10 and 4.9 versions. Did not include them in prior versions' upgrade doc.

### CODE REVIEW

**Comment by PaulAngus** [comment]
This should go in the specific upgrade procedures. it is not a headline.

**Comment by andrijapanicsb** [comment]
requesting docbuild

**Comment by andrijapanicsb** [comment]
requesting docbuild

**Comment by PaulAngus** [comment]
requesting docbuild

**Comment by PaulAngus** [comment]
requesting docbuild

**Comment by PaulAngus** [comment]
request docbuild

**Comment by PaulAngus** [comment]
ping @andrijapanicsb for review

**Comment by andrijapanicsb** [comment]
Minor grammar fixes and LGTM @PaulAngus

**Comment by andrijapanicsb** [comment]
wait one...

**Comment by andrijapanicsb** [comment]
requesting docbuild

**Comment by andrijapanicsb** [comment]
LGTM

**Pull request merged**
