### PR TITLE
Added documentation for the first class resource userdata

### PR DESCRIPTION
**Pull request by harikrishna-patnala**
This documentation is related to the changes made in PR https://github.com/apache/cloudstack/pull/6202.

Following are the changes made.
1. Userdata registration, listing and deleting under "Compute" tab
2. Providing registered userdata in "Add Instance" form
3. Linking userdata to template while registering/uploading/editing of a template/ISO
4. Explaining the userdata override policy while linking userdata to template

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan docbuild

**Comment by weizhouapache** [comment]
code lgtm
checked
http://qa.cloudstack.cloud/docs/WIP-PROOFING/pr/273/adminguide/templates.html
http://qa.cloudstack.cloud/docs/WIP-PROOFING/pr/273/adminguide/virtual_machines/user-data.html

@harikrishna-patnala 
would it be good to add a section to decribe how to use userdata parameters in cloud-config/jinja template ?

**Comment by harikrishna-patnala** [comment]
> code lgtm checked http://qa.cloudstack.cloud/docs/WIP-PROOFING/pr/273/adminguide/templates.html http://qa.cloudstack.cloud/docs/WIP-PROOFING/pr/273/adminguide/virtual_machines/user-data.html
> 
> @harikrishna-patnala would it be good to add a section to decribe how to use userdata parameters in cloud-config/jinja template ?

Thanks for the review @weizhouapache. I've now added them in the flow of userdata registration and during vm deployment. Please review again.

**Comment by weizhouapache** [comment]
@blueorangutan docbuild

**Comment by harikrishna-patnala** [comment]
@blueorangutan docbuild

**Review by vladimirpetrov — APPROVED** [review]
LGTM

**Pull request merged**
