### PR TITLE
4.13 Quick install guide updates

### PR DESCRIPTION
**Pull request by Spaceman1984**
This PR
Updates: 
- the cloudstack repo location, 
- the systemvm template location, 

And Adds:
- python-dns 
- mysql-connector-java downgrade

### CODE REVIEW

**Comment by andrijapanicsb** [comment]
@Spaceman1984 have you tested this locally - I mean following this edited guide/PR etc?

1) I recall that you need to remove/disable the mysql REPO and install/enable EPEL repo and just install the mysql-connector* without specifying versions - it will pick whatever are the current versions of python and java connectors (i.e. will pick up the python connector from the base centos repos, while the java connector will be pulled from the Epel - this is what we do in our templates/Trillian) - no need to specify exact versions and install python-dns, etc? But if you've tested with this edited guide, I'm fine with it (would just be more vague about 5.1.xxx version instead of targeting exact 5.1.25-3 version, so it the version in guide doesn't get obsolete in i.e. 3 months)

2) I would replace "4.11.3" with some variables, but that's minor.

thx

**Comment by andrijapanicsb** [comment]
In general, it's safer to have the mysql repo disabled, since a simple "yum upgrade" will probably upgrade the java connector and then the installation gets broken.

**Comment by andrijapanicsb** [comment]
requesting docbuild

**Comment by Spaceman1984** [comment]
> @Spaceman1984 have you tested this locally - I mean following this edited guide/PR etc?
> 
> 1. I recall that you need to remove/disable the mysql REPO and install/enable EPEL repo and just install the mysql-connector* without specifying versions - it will pick whatever are the current versions of python and java connectors (i.e. will pick up the python connector from the base centos repos, while the java connector will be pulled from the Epel - this is what we do in our templates/Trillian) - no need to specify exact versions and install python-dns, etc? But if you've tested with this edited guide, I'm fine with it (would just be more vague about 5.1.xxx version instead of targeting exact 5.1.25-3 version, so it the version in guide doesn't get obsolete in i.e. 3 months)
> 2. I would replace "4.11.3" with some variables, but that's minor.
> 
> thx

It seems like your way would be better. This is a workaround that worked for me while following the quick install guide.

**Comment by andrijapanicsb** [comment]
@Spaceman1984 thx for initiating this updated. Due to me not having (atm) time to properly update this release notes (and I like the warning improvement message) - for other few .rst files  - I've ported the latest changes to the PR #125 and will close this one.
If you have time to open a new PR against 4.13 and see what other /upgrade-4.1x.rst needs to be updates, that would be nice.

**Comment by andrijapanicsb** [comment]
requesting docbuild

**Comment by andrijapanicsb** [comment]
requesting docbuild

**Pull request merged**
