### PR TITLE
Replace obsolete apidocs links

### PR DESCRIPTION
**Pull request by onitake**
Many documents refer to the API documentation by an obsolete link that produces a 404.
This PR replaces all occurences of http://cloudstack.apache.org/docs/api/ with https://cloudstack.apache.org/api.html

Discovered in: #132

### CODE REVIEW

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
Lgtm can you rebase to 4.15 branch?

**Review by GabrielBrascher — APPROVED** [review]
Good catch, thanks for the PR @onitake.

LGTM

**Comment by onitake** [comment]
@rhtyd Sorry, what do you mean exactly?
* Rebase on 4.15 and keep the PR as-is (i.e. merge to master)?
* Rebase on 4.15 and change the merget target to 4.15?
* Submit a new, separate PR that targets 4.15 and keep this one?

**Comment by rhtyd** [comment]
Change base branch of the PR to 4.15 as this needs to go in 4.15

**Comment by onitake** [comment]
@rhtyd Like this?

**Comment by onitake** [comment]
@rhtyd Do you need me to resubmit a PR against master, or is this taken care of by the 4.15 commit?

**Comment by rhtyd** [comment]
No lgtm @onitake since you've changed base branch to 4.15, I've merged your PR on 4.15 branch and fwd-merge 4.15 to master.

**Pull request merged**
