### PR TITLE
Documentation for Object Storage feature

### PR DESCRIPTION
**Pull request by kishankavala**
Added documentation for Object Storage feature 

----
:books: Documentation preview :books:: https://cloudstack-documentation--338.org.readthedocs.build/en/338/

### CODE REVIEW

**Comment by kishankavala** [comment]
@blueorangutan docbuild

**Comment by kishankavala** [comment]
@blueorangutan docbuild

**Comment by vladimirpetrov** [comment]
@blueorangutan docbuild

**Comment by rohityadavcloud** [comment]
@kishankavala can you add some screenshot to forms, refer to other sections?

**Review by NuxRo — APPROVED** [review]
lgtm

**Comment by kishankavala** [comment]
@blueorangutan docbuild

**Comment by vishesh92** [comment]
@blueorangutan docbuild

**Comment by vladimirpetrov** [comment]
@blueorangutan docbuild

**Comment by vladimirpetrov** [comment]
@blueorangutan docbuild

**Comment by shwstppr** [comment]
@blueorangutan docbuild

**Comment by vladimirpetrov** [comment]
@blueorangutan docbuild

**Comment by vladimirpetrov** [comment]
@blueorangutan docbuild

**Comment by vladimirpetrov** [comment]
The link for one of the images is wrong, currently it is:

```
https://qa.cloudstack.cloud/builds/docs-build/pr/338/installguide/_static/images/add-object-storage.png
```

but the png is called 

```
source/_static/images/add-object-store.png
```

image

**Comment by shwstppr** [comment]
@blueorangutan docbuild

**Review by vladimirpetrov — APPROVED** [review]
LGTM

**Pull request merged**
