### PR TITLE
[ON HOLD FEATURE NOT READY] add getDiagnosticsData API and UI documentation 

### PR DESCRIPTION
**Pull request by PaulAngus**

### CODE REVIEW

**Comment by PaulAngus** [comment]
@BlueGitBot build

**Comment by PaulAngus** [comment]
@BlueGitBot build

**Comment by PaulAngus** [comment]
> @PaulAngus should commit [2b13684](https://github.com/apache/cloudstack-documentation/commit/2b136845739492decd2c27054f6cc5901aa283e1) be in here?

no @DaanHoogland  it's removed now.

**Comment by DaanHoogland** [comment]
not sure if this is still applicable, but if it is it will need an overhaul. closing.

**Pull request closed without merging**
