### PR TITLE
ScaleIO volume migration documentation

### PR DESCRIPTION
**Pull request by harikrishna-patnala**
This is related to the feature introduced here https://github.com/apache/cloudstack/pull/7408 to introduce volume migrations for Powerflex/ScaleIO storage

### CODE REVIEW

**Comment by harikrishna-patnala** [comment]
@blueorangutan docbuild

**Comment by harikrishna-patnala** [comment]
Added a new section here:
https://qa.cloudstack.cloud/builds/docs-build/pr/321/adminguide/virtual_machines.html#moving-vm-s-volumes-between-storage-pools-offline-volume-migration
image

and added a note for ScaleIO storage for live migration here:
https://qa.cloudstack.cloud/builds/docs-build/pr/321/adminguide/storage.html#migrating-a-vm-root-volume-to-a-new-storage-pool
image

**Comment by harikrishna-patnala** [comment]
@blueorangutan docbuild

**Comment by harikrishna-patnala** [comment]
Added a new section here:
https://qa.cloudstack.cloud/builds/docs-build/pr/321/adminguide/virtual_machines.html#moving-instance-s-volumes-between-storage-pools-offline-volume-migration
image

and added a note for ScaleIO storage for live migration here:
https://qa.cloudstack.cloud/builds/docs-build/pr/321/adminguide/storage.html#migrating-a-instance-root-volume-to-a-new-storage-pool
image

**Review by borisstoyanov — APPROVED** [review]
LGTM

**Review by weizhouapache — APPROVED** [review]

**Pull request merged**
