### PR TITLE
installguide: minor wording and grammar fixes

### PR DESCRIPTION
**Pull request by falcon78921**
Documentation improvements for building CloudStack from source.

### CODE REVIEW

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
requesting docbuild

**Review by GabrielBrascher — APPROVED** [review]

**Comment by rhtyd** [comment]
requesting docbuild

**Comment by DaanHoogland** [comment]
I don't like the over capitalisation taken from anglosaxon media, but overall this looks good. two lgtm so merging

**Comment by falcon78921** [comment]
Thank you for the feedback @DaanHoogland. I would be more than happy to create another pull request and reword the titles to use less capitalization, if you want. I just built packages for 4.14. As I install CloudStack again, I figured I would go through the documentation and improve where appropriate. I typically capitalize titles in documentation, but I can understand if they strike a non-neutral tone. I'll remember to use less capitalization for any future CloudStack PRs.

**Comment by DaanHoogland** [comment]
No worries @falcon78921 . thanks you for your contributions.

**Pull request merged**
