### PR TITLE
4.14.1.0 release work/docs

### PR DESCRIPTION
**Pull request by rhtyd**

### CODE REVIEW

**Comment by rhtyd** [comment]
requesting docbuild

**Comment by rhtyd** [comment]
@blueorangutan doc

**Comment by rhtyd** [comment]
requesting docbuild

**Comment by davidjumani** [comment]
@blueorangutan docbuild

**Comment by davidjumani** [comment]
@blueorangutan docbuild

**Comment by davidjumani** [comment]
@blueorangutan docbuild

**Comment by rhtyd** [comment]
cc @vladimirpetrov

**Pull request merged**
