### PR TITLE
network-offering: notes on vmware specific options

### PR DESCRIPTION
**Pull request by shwstppr**
Adds note for VMware specific network offering options used by corresponding VMware portgroup of the ACS network created using the network offering

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan docbuild

**Comment by shwstppr** [comment]
@blueorangutan docbuild

**Comment by shwstppr** [comment]
@blueorangutan docbuild

**Comment by shwstppr** [comment]
@alexandremattioli @NuxRo can you please review this

**Comment by shwstppr** [comment]
@blueorangutan docbuild

**Comment by shwstppr** [comment]
blueorangutan docbuild

**Review by rhtyd — APPROVED** [review]

**Pull request merged**
