### PR TITLE
4.16.1.0 release notes/docs updates

### PR DESCRIPTION
**Pull request by sureshanaparti**
4.16.1.0 release notes/docs updates

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan docbuild

**Review by DaanHoogland — APPROVED** [review]
looks good I didn't check completeness of the PR/issue tables but the contents looks good

**Comment by sureshanaparti** [comment]
@blueorangutan docbuild

**Comment by sureshanaparti** [comment]
@blueorangutan docbuild

**Review by nvazquez — APPROVED** [review]
LGTM

**Pull request merged**
